sudo: required
dist: trusty

language: cpp

compiler:
 - clang
 - gcc

script:
 - mkdir _build
 - cd _build
 - cmake ..
 - make -j4
 - _bin/utee-runner _bin/libagge.tests.so
 - _bin/utee-runner _bin/libagge.text.tests.so
 - _bin/utee-runner _bin/libagge.async.tests.so
